plugins {
    // Apply the scala Plugin to add support for Scala.
    id 'scala'

    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'

    id 'io.github.cosmicsilence.scalafix' version '0.2.9'

    // IntelliJ IDEA plugin to configure source/javadoc downloads
    id 'idea'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.jackson.databind
    implementation libs.jolt
    implementation libs.jsonpath
    implementation libs.logback.classic
    implementation libs.opentelemetry.sdk
    implementation libs.opentelemetry.sdk.autoconfig
    implementation libs.ox.core
    implementation libs.ox.kafka
    implementation libs.pureconfig.core
    implementation libs.pureconfig.generic
    implementation libs.pureconfig.yaml
    implementation libs.rocksdb
    implementation libs.scala.library
    implementation libs.scalalogging
    implementation libs.scallop
    implementation libs.tapir.core
    implementation libs.tapir.netty.server.sync

    testImplementation libs.commons.io
    testImplementation libs.embeddedkafka
    testImplementation libs.junit.platform.launcher
    testImplementation libs.kafka.clients
    testImplementation libs.kafka.metadata
    testImplementation libs.opentelemetry.sdk.testing
    testImplementation libs.scalatest
    testImplementation libs.tapir.sttp.stub4.server

    testRuntimeOnly libs.junit
    testRuntimeOnly libs.junit.platform.engine
}

scala {
    scalaVersion = '3.8.4'
}

tasks.withType(ScalaCompile) {
    scalaCompileOptions.additionalParameters = [
            '-encoding',
            'UTF-8',
            '-deprecation',
            '-feature',
            '-unchecked',
            '-source:3.8',
            '-release:25',
            '-Wunused:all']
}

application {
    mainClass = 'de.otto.capella.App'
}

test {
    useJUnitPlatform {
        includeEngines 'scalatest'
        testLogging {
            events('passed', 'skipped', 'failed')
        }
    }
}
